name: Linting

on: [pull_request]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint:prettier:check

  eslint:
    name: EsLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.14.0"

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint:eslint:check
